# Site settings
title: Saul Castañeda
email: phi.asesoria@gmail.com
url: https://github.com/sau-c/portfolio
description: "Aqui podras encontrar un poco de mi trabajo."
keywords: "ingeniero, electronica, telematica, redes, telecomunicaciones, portfolio"
skills: "Telecomunicaciones - Informática - Redes - Programación - Transmisión de datos - Sistemas embebidos - Ciberseguridad - Protocolos - Internet"
meta_author: Saul Castañeda

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0f0f0f #80B3FF
  primary-rgb: "15,15,15" #"128,179,255"
  secondary: ff9900 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Saul Castañeda
  location: Lugar
  social: Buscame en mis redes
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/sau-c

# Postal address (add as many lines as necessary)
address:
  - line: Area metropolitana CDMX

# # Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
